/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "Stm32_F103C6_gpio_driver.h"
#include "stm32f103x6.h"
void clockInit()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}
void GPIO_Init()
{
	GPIO_PinConfig_t PinCfg;
	//PA1 input highZ floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_IN_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//PB1 output push pull (speed 10M)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	PinCfg.GPIO_MODE = GPIO_MODE_OUT_PP;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//PA13 input high impedance
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_IN_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//PB7 (push pull ) output mode
	PinCfg.GPIO_PinNumber = GPIO_PIN_7;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	PinCfg.GPIO_MODE = GPIO_MODE_OUT_PP;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	//PB13 (push pull ) output mode
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	PinCfg.GPIO_MODE = GPIO_MODE_OUT_PP;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}
void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i = 0; i < time; i++)
		for(j = 0; j < 255; j++);
}
int main(void)
{
	clockInit();
	GPIO_Init();
	/* Loop forever */
	while(1)
	{
		//PA1 >>>> connected as external PUR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_Reset)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_Reset); //single pressing
		}
		//PA13 >>>> connected as external PDR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);

//			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET); //single pressing
		}
		wait_ms(1);

	}
}
